
processing:
   >>>  input==> test_faulthandler.py
   >>> saveAs==> test_faulthandler.1126_001321.py
   >>> output==> test_faulthandler.py

Traceback (most recent call last):
  File "/Users/klaus/.env/bin/addend", line 8, in <module>
    sys.exit(main())
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/command_line.py", line 4, in main
    addend.main()
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 953, in main
    type, data, cache = classify_lines(pydata)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 498, in classify_lines
    index = testMLComment(data, type, index)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 289, in testMLComment
    lineHas1Ldq = MLC1Ldq_regex.search(data[index])
IndexError: list index out of range

processing:
   >>>  input==> test_faulthandler.py
   >>> saveAs==> test_faulthandler.1126_001321.py
   >>> output==> test_faulthandler.py


   done: original input file saved as 'test_faulthandler.1126_001321.py'


processing:
   >>>  input==> test_faulthandler.py
   >>> output==> new.test_faulthandler.py

Traceback (most recent call last):
  File "/Users/klaus/.env/bin/addend", line 8, in <module>
    sys.exit(main())
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/command_line.py", line 4, in main
    addend.main()
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 953, in main
    type, data, cache = classify_lines(pydata)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 498, in classify_lines
    index = testMLComment(data, type, index)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 289, in testMLComment
    lineHas1Ldq = MLC1Ldq_regex.search(data[index])
IndexError: list index out of range
